[package]
name = "totorosay"
version = "0.1.0"
description = "cowsay but with totoro"
repository = "https://github.com/nicomyerr/totorosay"
readme = "README.md"
edition = "2021"

[lib]
name = "totorosay"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[dev-dependencies]
rstest = "0.25.0"
